@startuml

autonumber

actor Атакующий
box authentication_form
    participant SpringSecurity
    participant Serverlet
end box

loop неверные учетные\nданные пользователя
    Атакующий -> SpringSecurity: GET <b>http://localhost:8080/login.html</b>
    SpringSecurity -> SpringSecurity: пользователь не\nаутентифицирован
    SpringSecurity --> Атакующий: <b>200 OK</b>\nContent-Type: text/html;charset=UTF-8\n<form ... method="post" action="/login">\n  // username and password fields\n  <input name="_csrf" type="hidden" value="secretToken">\n</form>
    Атакующий -> SpringSecurity: POST <b>http://localhost:8080/login</b>\ncontent-type: application/x-www-form-urlencoded\nusername: user\npassword: wrongPassword\ncookie: JSESSIONID=ABC...\n_csrf: secretToken
end
SpringSecurity -> SpringSecurity: аутентификация\nпользователя
SpringSecurity -> Атакующий: <b>302 Found</b>\nSet-Cookie: JSESSIONID=BCD...;\nLocation: http://localhost:8080/hello.html?continue


@enduml